### ISSUE TITLE
KeyError: 'pop from an empty set'

### ISSUE THREAD

**Issue by icebear181818** [LiuXingMing/SinaSpider#25]
各位大神，为什么我运行出现下面的错误啊？
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 126, in _next_request
    request = next(slot.start_requests)
  File "C:\Users\chinchilla77\SinaSpider\Sina_spider1\Sina_spider1\spiders\spiders.py", line 22, in start_requests
    ID = self.scrawl_ID.pop()
KeyError: 'pop from an empty set'
新手，求帮助：（

**Comment by LiuXingMing** [comment]
待爬ID的集合为空
