### ISSUE TITLE
单机版运行缺少模块问题？

### ISSUE THREAD

**Issue by wgchen** [LiuXingMing/SinaSpider#3]
哥们你好，我一运行就提示ImportError: cannot import name CrawlSpider，想问一下CrawlSpider模块是系统自带的吗？还是自己写的，要是自己写的话能不能分享一下？

**Comment by LiuXingMing** [comment]
这是scrapy里面的类，估计是scrapy模块没装好。

**Comment by wgchen** [comment]
对，刚才是差了两个模块，现在我感觉都已经装好了呀，可是又报下面这个错误，因为cmdline.execute("scrapy crawl sinaSpider".split())函数实在不知道什么意思，有劳指点一下哪边出错了，或者说cmdline.execute()这个函数是干什么的？
C:\Python27\python.exe D:/PycharmProjects/Sina_spider1/Begin.py
Traceback (most recent call last):
  File "D:/PycharmProjects/Sina_spider1/Begin.py", line 3, in <module>
    cmdline.execute("scrapy crawl sinaSpider".split())
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc3-py2.7.egg\scrapy\cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc3-py2.7.egg\scrapy\utils\project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc3-py2.7.egg\scrapy\settings\__init__.py", line 285, in setmodule
    self.set(key, getattr(module, key), priority)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc3-py2.7.egg\scrapy\settings\__init__.py", line 260, in set
    self.attributes[name].set(value, priority)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc3-py2.7.egg\scrapy\settings\__init__.py", line 55, in set
    value = BaseSettings(value, priority=priority)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc3-py2.7.egg\scrapy\settings\__init__.py", line 91, in __init__
    self.update(values, priority)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc3-py2.7.egg\scrapy\settings\__init__.py", line 317, in update
    for name, value in six.iteritems(values):
  File "C:\Python27\lib\site-packages\six-1.10.0-py2.7.egg\six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'

Process finished with exit code 1

**Comment by LiuXingMing** [comment]
cmdline.execute()是用Python打开CMD窗口执行命令，你可以不用这个文件执行项目，直接打开CMD执行"scrapy crawl sinaSpider"也是一样的（注意路径）。

**Comment by vici0728** [comment]
我也是遇到这个问题 能请问一下 您用的scrapy版本吗 不同版本报错都不一样 @ LiuXingMing

**Comment by LiuXingMing** [comment]
scrapy1.0.5

**Comment by mengxiaoya1991** [comment]
你好，我也是遇到了这个问题：
Traceback (most recent call last):
  File "/home/mi/PycharmProjects/SinaSpider-master/Begin.py", line 3, in <module>
    cmdline.execute("scrapy crawl sinaSpider".split())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 285, in setmodule
    self.set(key, getattr(module, key), priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 260, in set
    self.attributes[name].set(value, priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 55, in set
    value = BaseSettings(value, priority=priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 91, in __init__
    self.update(values, priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 317, in update
    for name, value in six.iteritems(values):
  File "/usr/lib/python2.7/dist-packages/six.py", line 484, in iteritems
    return iter(getattr(d, _iteritems)(**kw))
AttributeError: 'list' object has no attribute 'iteritems'
请问应该怎么解决呢？是scrapy版本问题么？我用scrapy运行测试其他小demo都没有问题

**Comment by mengxiaoya1991** [comment]
已解决，详细方案可以参考我的提问8.
