### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by lnsyyj** [LiuXingMing/SinaSpider#62]
2017-08-15 00:20:29 [scrapy] ERROR: Error downloading <GET http://weibo.cn/5818747476/profile?filter=1&page=1>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/middleware.py", line 32, in process_request
    response = method(request=request, spider=spider)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/downloadermiddlewares/cookies.py", line 32, in process_request
    cookies = self._get_request_cookies(jar, request)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/downloadermiddlewares/cookies.py", line 87, in _get_request_cookies
    cookies = [self._format_cookie(x) for x in cookie_list]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/downloadermiddlewares/cookies.py", line 71, in _format_cookie
    cookie_str = '%s=%s' % (cookie['name'], cookie['value'])
TypeError: string indices must be integers, not str
2017-08-15 00:20:29 [scrapy] INFO: Closing spider (finished)
2017-08-15 00:20:29 [scrapy] INFO: Dumping Scrapy stats:

**Comment by leitang** [comment]
运行Spider1的时候我也遇到了同样的问题

**Comment by pythonmanGo** [comment]
同样的问题，无法继续！

**Comment by tanmq** [comment]
同样的问题，为毛呢？

**Comment by tanmq** [comment]
找到原因了，修改cookies.py文件的71行：
# return json.dumps(cookie)
 return cookie
不用转化json字符串，直接returncookie就好了

**Comment by mengjinglei** [comment]
@tanmq 可以提个pr修复一下

**Comment by cap-ljf** [comment]
@tanmq 感谢

**Comment by kilakila-heart** [comment]
@tanmq 感谢
