### ISSUE TITLE
单机版出现'list' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by OlafLee** [LiuXingMing/SinaSpider#9]
Traceback (most recent call last):
  File "Begin.py", line 3, in <module>
    cmdline.execute("scrapy crawl sinaSpider".split())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 285, in setmodule
    self.set(key, getattr(module, key), priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 260, in set
    self.attributes[name].set(value, priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 55, in set
    value = BaseSettings(value, priority=priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 91, in __init__
    self.update(values, priority)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 317, in update
    for name, value in six.iteritems(values):
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'

**Comment by mengxiaoya1991** [comment]
我之前也出现过,我记得好像是版本问题,你的scrapy版本对么?1.0.5

**Comment by mengxiaoya1991** [comment]
也有可能是没有安装pymongo

**Comment by OlafLee** [comment]
@mengxiaoya1991  果然是scrapy版本不对的原因，版本现在对了，可是现在启动之后会python已停止工作。。。

**Comment by mengxiaoya1991** [comment]
这个问题我没遇到过...你是什么系统啊?Linux么?估计是python没安好,我用的是2.7.6的.

**Comment by OlafLee** [comment]
windows，64位python，用的anaconda

**Comment by szthanatos** [comment]
之前的某些scrapy版本（包括现在的sina_spider2还没改过来）的setting里，ITEM_PIPELINES 是作为一个[]，但现在应该是一个字典，把 ["Sina_spider2.pipelines.MongoDBPipleline"]改为{"Sina_spider2.pipelines.MongoDBPipleline": 403,} 就可以了
